### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by dss91** [dev-0x7C6/fdt-viewer#4]
i am getting this following error

CMake Error at src/CMakeLists.txt:3 (add_subdirectory):
  The source directory

    /home/ubuntu/fdt-viewer/src/submodules/qhexview

  does not contain a CMakeLists.txt file.

**Comment by dev-0x7C6** [comment]
@dss91 Hi,

I'm suspecting that you need clone recursively or initialize submodules.
i.e. `git clone --recursive https://github.com/dev-0x7C6/fdt-viewer.git`

I need to correct steps in readme.md.

[more options here](https://stackoverflow.com/questions/3796927/how-to-git-clone-including-submodules)

**Comment by dev-0x7C6** [comment]
I'm assuming that issue is resolved, please reopen if not, thanks :)
