### ISSUE TITLE
Required QT Components

### ISSUE THREAD

**Issue by murrellr** [dev-0x7C6/fdt-viewer#7]
I'm trying to build this from the latest Ubuntu installation, but I am getting this warning:

CMake Warning at CMakeLists.txt:14 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.

What packages do I need to install to fix this?

**Comment by dev-0x7C6** [comment]
Hi,

I think you may need https://github.com/dev-0x7C6/fdt-viewer/blob/main/docker/Dockerfile#L16 (qtbase5-dev) installed aside compiler.

**Comment by theDimitron** [comment]
Hey,
Just so you know: I have the same issue with Qt6. Although I've installed Qt6 on my PC and export the variable, it did not solve the problem
So I just took v. 0.8.1 with old Qt and it worked fine.
Or do you know the new package should I install?

**Comment by dev-0x7C6** [comment]
@theDimitron  probably similar packages to qtbase5-dev , i.e. qt6-base-dev (maybe similar headers are also needed). Qt6 version is under development I would recommend to stick with Qt5 for now.
